### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TheCuddleDoodle** [aquaticus/esp32_composite_video_demo#1]
/__idf_main.dir/demo.c.obj -c ../main/demo.c
../main/demo.c:131:27: error: unknown type name 'esp_chip_model_t'; did you mean 'esp_ip_addr_t'?
 const char* get_chip_name(esp_chip_model_t model)

**Comment by aquaticus** [comment]
What version of ESP-IDF you're using. The function exists for sure for version 4.3 and 4.4.

**Comment by callimero** [comment]
May be a problem that you mostly get 4.2 when you go on their webpages to download.

It fails because 4.2 doesn not know the S2.

**Comment by callimero** [comment]
I am quite out of my comfort zone here...

Looks it is in esp32_composite_video_lib and missing a file there? maybe my install is corrupted?

`
67%] Building C object esp-idf/esp32_composite_video_lib/CMakeFiles/__idf_esp32_composite_video_lib.dir/video.c.obj
[ 68%] Built target __idf_esp_adc_cal
[ 68%] Built target __idf_esp_hid
[ 69%] Built target __idf_espcoredump
[ 70%] Built target __idf_esp_lcd
[ 71%] Built target __idf_wear_levelling
/home/cw/esp/esp-idf/components/esp32_composite_video_lib/video.c:34:10: fatal error: driver/periph_ctrl.h: No such file or directory
 #include "driver/periph_ctrl.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[ 75%] Built target __idf_freemodbus
[ 75%] Built target __idf_perfmon
make[2]: *** [esp-idf/esp32_composite_video_lib/CMakeFiles/__idf_esp32_composite_video_lib.dir/build.make:76: esp-idf/esp32_composite_video_lib/CMakeFiles/__idf_esp32_composite_video_lib.dir/video.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:4152: esp-idf/esp32_composite_video_lib/CMakeFiles/__idf_esp32_composite_video_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 76%] Built target __idf_spiffs
[ 76%] Built target __idf_mqtt
Scanning dependencies of target __idf_protocomm
Scanning dependencies of target __idf_mdns
[ 76%] Building C object esp-idf/mdns/CMakeFiles/__idf_mdns.dir/mdns.c.obj
[ 76%] Building C object esp-idf/mdns/CMakeFiles/__idf_mdns.dir/mdns_networking_lwip.c.obj
[ 77%] Building C object esp-idf/mdns/CMakeFiles/__idf_mdns.dir/mdns_console.c.obj
[ 94%] Built target __idf_lvgl
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/common/protocomm.c.obj
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/security/security0.c.obj
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/security/security1.c.obj
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/proto-c/constants.pb-c.c.obj
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/proto-c/sec0.pb-c.c.obj
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/proto-c/sec1.pb-c.c.obj
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/proto-c/session.pb-c.c.obj
[ 94%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/transports/protocomm_console.c.obj
[ 95%] Building C object esp-idf/protocomm/CMakeFiles/__idf_protocomm.dir/src/transports/protocomm_httpd.c.obj
[ 95%] Linking C static library libprotocomm.a
[ 95%] Built target __idf_protocomm
[ 95%] Linking C static library libmdns.a
[ 95%] Built target __idf_mdns
make: *** [Makefile:130: all] Error 2
make failed with exit code 2
`

**Comment by callimero** [comment]
it is now in `driver/periph_ctrl.h`. I installed master and thats towards 5.0 :/

Dang this is getting over my head.

**Comment by callimero** [comment]
Ufff. Coming from 4.2, accidentally installed master (5.0), now on 4.4 it compiles...

Just to say. That was no fun :)

**Comment by callimero** [comment]
Success! Video on oscilloscope and TV :)

**Comment by TheCuddleDoodle** [comment]
Yes using 4.4 solves the problem.
